baseURL='https://rolletquentin.com/blog/'
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true
theme = 'chameleon-theme'

[languages]
  [languages.en-us]
    contentDir = 'content/en-us'
    languageCode = 'en-US'
    title = "Quentin's blog"
    languageName = "English"
    weight = 1
  [languages.fr]
    contentDir = "content/fr"
    languageCode = 'fr-FR'
    title = "Blog de Quentin"
    languageName = "Français"
    weight = 2


