baseURL='http://rolletquentin.com/blog/'
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true
theme = 'hyde'

[languages]
  [languages.en-us]
    contentDir = 'content/en-us'
    languageCode = 'en-US'
    title = "Quentin's blog"
    languageName = "English"
    weight = 1
    [languages.en-us.params]
      description = "My personnal blog."
  [languages.fr]
    contentDir = "content/fr"
    languageCode = 'fr-FR'
    title = "Blog de Quentin"
    languageName = "Français"
    weight = 2
    [languages.fr.params]
      description = "Mon blog personnel."

